Export entrypoints to csv output
spgroup/static-semantic-merge pull request #5
Opened 2024-05-30 18:14 UTC by barbosamaatheus

2024-05-30 20:07 UTC, pauloborba requested changes

2024-05-30 20:07 UTC, pauloborba commented on src/main/java/main/StaticAnalysisMerge.java
> +                //mergeManager.revertCommint(mergeCommit.getLeftSHA());
@barbosamaatheus por que não remover logo a linha?

2024-05-30 22:30 UTC, Vinicius-resende-cin requested changes
Por algum motivo o problema com os paths para as pastas dependencies e scripts voltou a acontecer. Para resolver isso é preciso o seguinte:
- Adicionar uma opção de linha de comando para receber o caminho para a pasta de scripts e passar o valor para o construtor do `generateSootInputFilesOutputProcessor` em `StaticAnalysisMerge.java`
- Passar o valor (já recebido pela opção 'ssm') para o construtor do `runSootAnalysisOutputProcessor` no mesmo arquivo

Além disso, quando resolvo esse problema localmente e executo as análises todas retornam o mesmo erro:
```
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439)
        at soot.asm.AsmClassSource.resolve(AsmClassSource.java:65)
        at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:240)
        at soot.SootResolver.bringToHierarchy(SootResolver.java:214)
        at soot.SootResolver.bringToSignatures(SootResolver.java:279)
        at soot.SootResolver.bringToBodies(SootResolver.java:319)
        at soot.SootResolver.processResolveWorklist(SootResolver.java:164)
        at soot.SootResolver.resolveClass(SootResolver.java:134)
        at soot.Scene.loadClass(Scene.java:942)
        at soot.Scene.loadClassAndSupport(Scene.java:927)
        at soot.Scene.loadNecessaryClasses(Scene.java:1753)
        at br.unb.cic.analysis.SootWrapper.configureSootOptionsToRunInterproceduralOverrideAssignmentAnalysis(SootWrapper.java:77)
        at br.unb.cic.analysis.Main.runOverrideAssignmentAnalysis(Main.java:301)
        at br.unb.cic.analysis.Main.runAnalysis(Main.java:201)
        at br.unb.cic.analysis.Main.main(Main.java:76)
```

2024-05-30 22:33 UTC, Vinicius-resende-cin requested changes
Por algum motivo o problema com os paths para as pastas dependencies e scripts voltou a acontecer. Para resolver isso é preciso o seguinte:
- Adicionar uma opção de linha de comando para receber o caminho para a pasta de scripts e passar o valor para o construtor do `generateSootInputFilesOutputProcessor` em `StaticAnalysisMerge.java`
- Passar o valor (já recebido pela opção 'ssm') para o construtor do `runSootAnalysisOutputProcessor` no mesmo arquivo

Além disso, quando resolvo esse problema localmente e executo as análises todas retornam o mesmo erro:
```
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439)
        at soot.asm.AsmClassSource.resolve(AsmClassSource.java:65)
        at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:240)
        at soot.SootResolver.bringToHierarchy(SootResolver.java:214)
        at soot.SootResolver.bringToSignatures(SootResolver.java:279)
        at soot.SootResolver.bringToBodies(SootResolver.java:319)
        at soot.SootResolver.processResolveWorklist(SootResolver.java:164)
        at soot.SootResolver.resolveClass(SootResolver.java:134)
        at soot.Scene.loadClass(Scene.java:942)
        at soot.Scene.loadClassAndSupport(Scene.java:927)
        at soot.Scene.loadNecessaryClasses(Scene.java:1753)
        at br.unb.cic.analysis.SootWrapper.configureSootOptionsToRunInterproceduralOverrideAssignmentAnalysis(SootWrapper.java:77)
        at br.unb.cic.analysis.Main.runOverrideAssignmentAnalysis(Main.java:301)
        at br.unb.cic.analysis.Main.runAnalysis(Main.java:201)
        at br.unb.cic.analysis.Main.main(Main.java:76)
```

2024-06-02 13:52 UTC, barbosamaatheus commented on src/main/java/main/StaticAnalysisMerge.java
> +                //mergeManager.revertCommint(mergeCommit.getLeftSHA());
Vamos precisar dessa linhas. Eu tinha comentado localmente e acabou indo no commit. Mas vou descomentar.

2024-06-02 19:25 UTC, barbosamaatheus commented
> Por algum motivo o problema com os paths para as pastas dependencies e scripts voltou a acontecer. Para resolver isso é preciso o seguinte:
> 
> * Adicionar uma opção de linha de comando para receber o caminho para a pasta de scripts e passar o valor para o construtor do `generateSootInputFilesOutputProcessor` em `StaticAnalysisMerge.java`
> * Passar o valor (já recebido pela opção 'ssm') para o construtor do `runSootAnalysisOutputProcessor` no mesmo arquivo
> 
> Além disso, quando resolvo esse problema localmente e executo as análises todas retornam o mesmo erro:
> 
> ```
> java.lang.IllegalArgumentException
>         at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185)
>         at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168)
>         at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439)
>         at soot.asm.AsmClassSource.resolve(AsmClassSource.java:65)
>         at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:240)
>         at soot.SootResolver.bringToHierarchy(SootResolver.java:214)
>         at soot.SootResolver.bringToSignatures(SootResolver.java:279)
>         at soot.SootResolver.bringToBodies(SootResolver.java:319)
>         at soot.SootResolver.processResolveWorklist(SootResolver.java:164)
>         at soot.SootResolver.resolveClass(SootResolver.java:134)
>         at soot.Scene.loadClass(Scene.java:942)
>         at soot.Scene.loadClassAndSupport(Scene.java:927)
>         at soot.Scene.loadNecessaryClasses(Scene.java:1753)
>         at br.unb.cic.analysis.SootWrapper.configureSootOptionsToRunInterproceduralOverrideAssignmentAnalysis(SootWrapper.java:77)
>         at br.unb.cic.analysis.Main.runOverrideAssignmentAnalysis(Main.java:301)
>         at br.unb.cic.analysis.Main.runAnalysis(Main.java:201)
>         at br.unb.cic.analysis.Main.main(Main.java:76)
> ```

@Vinicius-resende-cin o problema com o path provavelmente se da por uma alteração no mining. 
Você pode ver nesse [commit](https://github.com/spgroup/miningframework/pull/192/commits/3a52fd1b169bf9a29e2da61d53e949feae9f0165) no arquivo `src/main/services/outputProcessors/GenerateSootInputFilesOutputProcessor.groovy`. 

Fiz essa mudança, pois em meu debug percebi que o script estava duplicando o caminho. 
Como você resolveu por ai localmente?  Pode me enviar por favor?  Dá uma olhada tbm na alteração la no mining, o PR ainda está aberto. 

Sobre o erro, percebi que é um erro da análise em si, não consegui replicar aqui, pode me da mais detalhes de como você chegou nesse ponto?

2024-06-03 11:51 UTC, pauloborba commented on src/main/java/main/StaticAnalysisMerge.java
> +                //mergeManager.revertCommint(mergeCommit.getLeftSHA());
@barbosamaatheus também há um erro no nome revertCommiNt

2024-06-05 19:59 UTC, Vinicius-resende-cin approved these changes
O problema com os paths foi resolvido, mas o erro das análises continua. Como esse erro acontece durante as análises em si, acredito fazer mais sentido resolver no repositório correspondente.

2024-06-05 21:41 UTC, Vinicius-resende-cin commented
Eu acredito ter encontrado o problema. Vou mandar os detalhes no slack.

2024-06-06 17:44 UTC, barbosamaatheus commented
> O problema com os paths foi resolvido, mas o erro das análises continua. Como esse erro acontece durante as análises em si, acredito fazer mais sentido resolver no repositório correspondente.

@Vinicius-resende-cin você obtém o mesmo erro quando executar a análise na versão deste [PR](https://github.com/spgroup/conflict-static-analysis/pull/89)??

A versão que está nas dependências aqui é a mesma gerada lá.

2024-06-06 18:39 UTC, Vinicius-resende-cin commented
> > O problema com os paths foi resolvido, mas o erro das análises continua. Como esse erro acontece durante as análises em si, acredito fazer mais sentido resolver no repositório correspondente.
> 
> @Vinicius-resende-cin você obtém o mesmo erro quando executar a análise na versão deste [PR](https://github.com/spgroup/conflict-static-analysis/pull/89)??
> 
> A versão que está nas dependências aqui é a mesma gerada lá. 

Sim, fiz os testes utilizando essa versão das análizes como base.

2024-06-07 20:01 UTC, galilasmb commented on src/main/java/csvManager/CsvManager.java
> -            writer.close();
Não faltuo fechar o arquivo?

2024-06-11 19:20 UTC, pauloborba approved these changes

2024-06-12 16:41 UTC, barbosamaatheus commented on src/main/java/csvManager/CsvManager.java
> -            writer.close();
o Java garante automaticamente que os recursos serão fechados no final do bloco try

2024-06-13 15:23 UTC, galilasmb approved these changes

2024-06-13 17:37 UTC, merged